# Generated by Django 4.2.7 on 2023-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itemdemenu_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemenu',
            name='categoria',
            field=models.CharField(choices=[('COMIDAS', 'Comidas'), ('BEBIDAS', 'Bebidas')], default='', max_length=100),
        ),
    ]
