# Generated by Django 4.2.7 on 2023-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_itemdemenu_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemenu',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
