# Generated by Django 4.2.7 on 2023-12-04 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_itemdemenu_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdemenu',
            name='data_item',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
