# Generated by Django 4.2.7 on 2023-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_itemdemenu_data_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdemenu',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
